import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SNS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// #Layout 계층 구조
// RootLayout -> [Page]Layout -> [Page]

// tailwind => 호불호 너무 심하고, 가독성 X
// Styled Component => Server Component SSR issue
// sass
// css module
// vanilla extract => Windows issue
